{{- range $key, $value := .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}
spec:
  accessModes: {{ $value.accessModes }}
  resources:
    requests:
      storage: {{ $value.size }}
{{- end }}